### ISSUE TITLE
activating chrome / edge profile

### ISSUE THREAD

**Issue by obar1** [jwbargsten/defbro#1]
hi  @jwbargsten 
>thanks for this handy tool

much better than what I used so  far
```
(py37) √ main % alias
dgc='open -a "Google Chrome" --args --make-default-browser'
dme='open -a "Microsoft Edge" --args --make-default-browser'
```
can you  add this as feature?
so I set the current profile too?

![image](https://user-images.githubusercontent.com/387386/126758829-1a0d35d2-1bd4-4f7e-b2e9-4590af04c45e.png)

**Comment by jwbargsten** [comment]
Hi @obar1, I'm afraid I need more information to help you with this. I currently don't know exactly what feature you suggest. From what I read in your description, I get the feeling that your feature request might be slightly out of scope for `defbro`.

**Comment by jwbargsten** [comment]
It seems to be stale, so I'll close this issue for now. We can always re-open if needed!
