### ISSUE TITLE
Error install from homebrew

### ISSUE THREAD

**Issue by skofli** [jwbargsten/defbro#4]
`warning: 'defbro-0.0.1': failed loading cached manifest for 'defbro-0.0.1': Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “manifests” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/user_name/Library/Caches/org.swift.swiftpm/manifests, NSUnderlyingError=0x6000013b4990 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: 'defbro-0.0.1': failed closing cache: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “manifests” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/user_name/Library/Caches/org.swift.swiftpm/manifests, NSUnderlyingError=0x6000013bfc30 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error: 'defbro-0.0.1': Invalid manifest
/private/tmp/defbro-20230117-12819-gal0kl/defbro-0.0.1/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription`

MacOS Ventura 13.1
M1 Pro

**Comment by jwbargsten** [comment]
Yeah, annoying. I think this might be the solution: https://stackoverflow.com/questions/39795455/no-such-module-packagedescription/74768544#74768544

Unfortunately Github runners do not support M1, yet. So you have to download Xcode from the app store.

**Comment by skofli** [comment]
This worked for me. Thank you

**Comment by rgl** [comment]
@jwbargsten, FYI, [cirrus ci](https://cirrus-ci.org) supports arm64 builds. You can see my example at https://github.com/rgl/security-add-trusted-cert/blob/main/.cirrus.yml.
