### ISSUE TITLE
Raycast support

### ISSUE THREAD

**Issue by jfernandogt** [jwbargsten/defbro#6]
I'm not sure if you still maintain this repo, but I found it while looking for a tool like this. Instead of using the command tool, I wanted to do it through Raycast.

So here's the PR: https://github.com/raycast/extensions/pull/15356
I hope it will merge in a couple of days.

**Comment by jwbargsten** [comment]
neat!

**Comment by jfernandogt** [comment]
If anyone encounters this topic, here's the link to the Raycast extension: https://www.raycast.com/fernando_barrios/defbro
